import type { Metadata } from "next";
import { Inter, Pattaya } from "next/font/google";

import "./globals.css";

import { Toaster } from "sonner";

import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

const pattaya = Pattaya({
  subsets: ["latin"],
  variable: "--font-pattaya",
  weight: "400",
});

export const metadata: Metadata = {
  title: "MealMap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          pattaya.variable,
          "min-h-screen bg-[#F9EFDB]",
        )}
      >
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
